name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.0.4+2
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  cloud_firestore: ^4.0.2
  provider: ^6.0.2
  preload_page_view: ^0.1.6

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
